default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: edahi_database
  username: edahi
  password: Ed_95611189  # Deja vacío si no tienes contraseña
  host: localhost
  port: 5432

test:
  <<: *default
  database: tu_app_test

production:
  <<: *default
  database: edahi_database
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432

  # Configuración específica para Action Cable
  cable:
    adapter: redis
    url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>