services:
  - type: web
    name: alpha-blog
    env: production
    buildCommand: "./bin/render-build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edahi_database
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString